name: 'outetts_dart'
description: 'Wip OuteTTS Is Library for generate neural Text To Speech on Edge Device Without api key or internet quota'
version: '0.0.3'
topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'
  - 'whisper'
  - 'text-to-speech'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  outetts: '^0.0.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/outetts'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
